language: cpp

sudo: required

cache: 
 apt: true

env:
 - BOOST_PATH=/usr BOOST_LIB_PATH=/usr/lib PROTOBUF_PATH=/usr

addons:
 apt:
  packages:
   - libboost-all-dev

dist: trusty
compiler:
 - clang
 - g++

os:
 - linux

before_install:
 - sudo add-apt-repository -y ppa:edd/misc
 - sudo apt-get -qq update
 - sudo apt-get install -qq libprotobuf10 protobuf-compiler
 - sudo apt-get install -qq qt5-default
 - sudo apt-get install --yes doxygen graphviz
 
install: true

script:
 - doxygen alpha.protort.doxygen
 - qmake -qt=qt5 -v
 - qmake -qt=qt5
 - make
 - protocol/bin/alpha.protort.protocol.autotests
 - link/bin/alpha.protort.link.autotests 
 - terminal/bin/alpha.protort.terminal.autotests
 - components/bin/alpha.protort.components.autotests
 - cd parser/tests/auto/bin && ./alpha.protort.parser.autotests 
 - cd ../../../../node/bin/ && sudo ./alpha.protort.node.autotests
 
notifications:
 email:
  recipients:
  on_success: never
  on_failure: always
  
